/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as AiFilmmakerRouteImport } from './routes/ai-filmmaker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as JournalGrokImagineVideo15AiVideoRouteImport } from './routes/journal/grok-imagine-video-1-5-ai-video'
import { Route as ApiPublicBlueprintDownloadRouteImport } from './routes/api/public/blueprint/download'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFilmmakerRoute = AiFilmmakerRouteImport.update({
  id: '/ai-filmmaker',
  path: '/ai-filmmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const JournalGrokImagineVideo15AiVideoRoute =
  JournalGrokImagineVideo15AiVideoRouteImport.update({
    id: '/grok-imagine-video-1-5-ai-video',
    path: '/grok-imagine-video-1-5-ai-video',
    getParentRoute: () => JournalRoute,
  } as any)
const ApiPublicBlueprintDownloadRoute =
  ApiPublicBlueprintDownloadRouteImport.update({
    id: '/api/public/blueprint/download',
    path: '/api/public/blueprint/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-filmmaker': typeof AiFilmmakerRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/journal/grok-imagine-video-1-5-ai-video': typeof JournalGrokImagineVideo15AiVideoRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/api/public/blueprint/download': typeof ApiPublicBlueprintDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-filmmaker': typeof AiFilmmakerRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/journal/grok-imagine-video-1-5-ai-video': typeof JournalGrokImagineVideo15AiVideoRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal': typeof JournalIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/api/public/blueprint/download': typeof ApiPublicBlueprintDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-filmmaker': typeof AiFilmmakerRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/journal/grok-imagine-video-1-5-ai-video': typeof JournalGrokImagineVideo15AiVideoRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/api/public/blueprint/download': typeof ApiPublicBlueprintDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-filmmaker'
    | '/blueprint'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/portfolio'
    | '/pricing'
    | '/sitemap.xml'
    | '/journal/grok-imagine-video-1-5-ai-video'
    | '/portfolio/$slug'
    | '/journal/'
    | '/portfolio/'
    | '/api/public/blueprint/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-filmmaker'
    | '/blueprint'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/sitemap.xml'
    | '/journal/grok-imagine-video-1-5-ai-video'
    | '/portfolio/$slug'
    | '/journal'
    | '/portfolio'
    | '/api/public/blueprint/download'
  id:
    | '__root__'
    | '/'
    | '/ai-filmmaker'
    | '/blueprint'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/portfolio'
    | '/pricing'
    | '/sitemap.xml'
    | '/journal/grok-imagine-video-1-5-ai-video'
    | '/portfolio/$slug'
    | '/journal/'
    | '/portfolio/'
    | '/api/public/blueprint/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiFilmmakerRoute: typeof AiFilmmakerRoute
  BlueprintRoute: typeof BlueprintRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JournalRoute: typeof JournalRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBlueprintDownloadRoute: typeof ApiPublicBlueprintDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-filmmaker': {
      id: '/ai-filmmaker'
      path: '/ai-filmmaker'
      fullPath: '/ai-filmmaker'
      preLoaderRoute: typeof AiFilmmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/journal/grok-imagine-video-1-5-ai-video': {
      id: '/journal/grok-imagine-video-1-5-ai-video'
      path: '/grok-imagine-video-1-5-ai-video'
      fullPath: '/journal/grok-imagine-video-1-5-ai-video'
      preLoaderRoute: typeof JournalGrokImagineVideo15AiVideoRouteImport
      parentRoute: typeof JournalRoute
    }
    '/api/public/blueprint/download': {
      id: '/api/public/blueprint/download'
      path: '/api/public/blueprint/download'
      fullPath: '/api/public/blueprint/download'
      preLoaderRoute: typeof ApiPublicBlueprintDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalRouteChildren {
  JournalGrokImagineVideo15AiVideoRoute: typeof JournalGrokImagineVideo15AiVideoRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalGrokImagineVideo15AiVideoRoute: JournalGrokImagineVideo15AiVideoRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiFilmmakerRoute: AiFilmmakerRoute,
  BlueprintRoute: BlueprintRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JournalRoute: JournalRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBlueprintDownloadRoute: ApiPublicBlueprintDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
